sudo: false
branches:
  only:
    - master
    - gh-publish # @todo remove

language: node_js

# @todo ignore PRs
after_success:
  - echo 'Publishing to GitHub Pages'
  - git config user.name 'TravisCI Auto-publisher'
  - git config user.email 'travis-auto-publish@example.com'
  - printf '#!/bin/sh -e\necho %s' "$GH_PUBLISH_TOKEN" > gh-publish-pass.sh && chmod u+x gh-publish-pass.sh
  - node_modules/.bin/browserify index.js > index-browserify.js && mv index-browserify.js index.js &&
    git add index.js && git commit -m 'Auto-publishing via TravisCI [skip ci]' &&
    GIT_ASKPASS=./gh-publish-pass.sh git push origin +HEAD:gh-pages
